Repository internetarchive/Zeno, pull requests merged in 2024-07, with the labels that each got.

#66 Give Zeno the logging it deserves
  .gitignore
  cmd/cmd.go
  cmd/utils.go
  config/config.go
  go.mod
  go.sum
  internal/pkg/crawl/api.go
  internal/pkg/crawl/assets.go
  internal/pkg/crawl/capture.go
  internal/pkg/crawl/crawl.go
  internal/pkg/crawl/finish.go
  internal/pkg/crawl/hq.go
  internal/pkg/crawl/log.go
  internal/pkg/frontier/frontier.go
  internal/pkg/log/elasticsearch.go
  internal/pkg/log/file.go
  internal/pkg/log/log.go
  internal/pkg/log/misc.go
  internal/pkg/log/multi_handler.go
  internal/pkg/log/rotate.go
  internal/pkg/log/withfields.go
  internal/pkg/log/writer.go
Labels: enhancement

#76 Add deduping stats
  go.mod
  go.sum
  internal/pkg/crawl/api.go
  internal/pkg/crawl/stats.go
Labels: enhancement

#75 Remove Gin dependency
  cmd/cmd.go
  cmd/utils.go
  config/config.go
  go.mod
  go.sum
  internal/pkg/crawl/api.go
  internal/pkg/crawl/capture.go
  internal/pkg/crawl/crawl.go
Labels: enhancement

#79 Fix crash when --api is not set
  cmd/utils.go
  internal/pkg/crawl/capture.go
Labels: bug

#67 Rewrite of cmd+config packages using `spf13` `cobra` and `viper`
  .gitignore
  cmd/all/all.go
  cmd/cmd.go
  cmd/get.go
  cmd/get/get.go
  cmd/get/hq.go
  cmd/get/list.go
  cmd/get/url.go
  cmd/get_hq.go
  cmd/get_list.go
  cmd/get_url.go
  cmd/utils.go
  cmd/version/deps.go
  cmd/version/version.go
  config/config.go
  go.mod
  go.sum
  internal/pkg/crawl/api.go
  internal/pkg/crawl/config.go
  internal/pkg/crawl/crawl.go
  internal/pkg/log/log.go
  main.go
Labels: enhancement

#80 Fix workers not stopping properly and temp fix for workers hanging unexpectedly
  cmd/get.go
  internal/pkg/crawl/api.go
  internal/pkg/crawl/capture.go
  internal/pkg/crawl/config.go
  internal/pkg/crawl/crawl.go
  internal/pkg/crawl/finish.go
  internal/pkg/crawl/hq.go
  internal/pkg/crawl/stats.go
  internal/pkg/crawl/utils.go
  internal/pkg/crawl/worker.go
  internal/pkg/crawl/worker_pool.go
Labels: bug

#91 Fix commit hash in User Agent can't be calculated when not present
  internal/pkg/crawl/config.go
  internal/pkg/utils/version.go
Labels: bug

#93 Persist & load queue stats
  internal/pkg/queue/dequeue.go
  internal/pkg/queue/enqueue.go
  internal/pkg/queue/enqueue_test.go
  internal/pkg/queue/metadata.go
  internal/pkg/queue/queue.go
  internal/pkg/queue/stats.go
Labels: enhancement, internal-only

#99 Implement host rotation and Enqueue/Dequeue access regulation via atomic booleans
  .gitignore
  internal/pkg/crawl/finish.go
  internal/pkg/crawl/stats.go
  internal/pkg/crawl/worker.go
  internal/pkg/queue/access.go
  internal/pkg/queue/access_test.go
  internal/pkg/queue/dequeue.go
  internal/pkg/queue/enqueue.go
  internal/pkg/queue/metadata.go
  internal/pkg/queue/queue.go
  internal/pkg/queue/queue_test.go
Labels: enhancement, internal-only

#101 Have `queue.Enqueue()` handover items to idle workers and optimize workers routines
  internal/pkg/crawl/worker.go
  internal/pkg/queue/enqueue.go
  internal/pkg/queue/handover.go
  internal/pkg/queue/queue.go
Labels: enhancement, internal-only

#95 Implement linkheader parsing
  go.mod
  go.sum
  internal/pkg/crawl/capture.go
  internal/pkg/crawl/link_header.go
  internal/pkg/crawl/link_header_test.go
Labels: enhancement
