Repository internetarchive/Zeno, pull requests merged in 2024-08, with the labels that each got.

#104 Optimize `get list` loading performance
  internal/pkg/queue/item.go
Labels: enhancement

#105 Remove `runtime.Gosched()` in polling
  internal/pkg/crawl/worker.go
Labels: enhancement

#106 Queue handover v2
  cmd/get.go
  config/config.go
  internal/pkg/crawl/api.go
  internal/pkg/crawl/config.go
  internal/pkg/crawl/crawl.go
  internal/pkg/crawl/hq.go
  internal/pkg/crawl/stats.go
  internal/pkg/crawl/worker.go
  internal/pkg/crawl/worker_pool.go
  internal/pkg/queue/access_test.go
  internal/pkg/queue/dequeue.go
  internal/pkg/queue/dequeue_test.go
  internal/pkg/queue/enqueue.go
  internal/pkg/queue/enqueue_test.go
  internal/pkg/queue/handover.go
  internal/pkg/queue/handover_test.go
  internal/pkg/queue/queue.go
  internal/pkg/queue/queue_test.go
  internal/pkg/queue/stats.go
Labels: enhancement, internal-only

#107 Improve WAL concurrency performance
  internal/pkg/crawl/api.go
  internal/pkg/crawl/crawl.go
  internal/pkg/crawl/hq.go
  internal/pkg/crawl/outlinks.go
  internal/pkg/queue/dequeue.go
  internal/pkg/queue/dequeue_test.go
  internal/pkg/queue/enqueue.go
  internal/pkg/queue/enqueue_test.go
  internal/pkg/queue/index/manager.go
  internal/pkg/queue/index/manager_test.go
  internal/pkg/queue/index/recovery_test.go
  internal/pkg/queue/index/wal.go
  internal/pkg/queue/index/wal_test.go
  internal/pkg/queue/metadata.go
  internal/pkg/queue/queue.go
  internal/pkg/queue/queue_test.go
  internal/pkg/queue/stats.go
Labels: enhancement

#78 Rewriting the queue
  .github/workflows/go.yml
  .gitignore
  cmd/get.go
  cmd/get_list.go
  cmd/get_url.go
  config/config.go
  go.mod
  go.sum
  internal/pkg/crawl/api.go
  internal/pkg/crawl/assets.go
  internal/pkg/crawl/capture.go
  internal/pkg/crawl/config.go
  internal/pkg/crawl/crawl.go
  internal/pkg/crawl/finish.go
  internal/pkg/crawl/hq.go
  internal/pkg/crawl/log.go
  internal/pkg/crawl/outlinks.go
  internal/pkg/crawl/stats.go
  internal/pkg/crawl/utils.go
  internal/pkg/crawl/worker.go
  internal/pkg/crawl/worker_pool.go
  internal/pkg/frontier/frontier.go
  internal/pkg/frontier/host_pool.go
  internal/pkg/frontier/item.go
  internal/pkg/frontier/manager.go
  internal/pkg/frontier/persistent_queue.go
  internal/pkg/frontier/save.go
  internal/pkg/frontier/seencheck.go
  internal/pkg/frontier/utils.go
  internal/pkg/queue/access.go
  internal/pkg/queue/access_test.go
  internal/pkg/queue/dequeue.go
  internal/pkg/queue/dequeue_test.go
  internal/pkg/queue/encoding.go
  internal/pkg/queue/encoding_test.go
  internal/pkg/queue/enqueue.go
  internal/pkg/queue/enqueue_test.go
  internal/pkg/queue/error.go
  internal/pkg/queue/handover.go
  internal/pkg/queue/handover_test.go
  internal/pkg/queue/index/encoding.go
  internal/pkg/queue/index/error.go
  internal/pkg/queue/index/file_io.go
  internal/pkg/queue/index/index.go
  internal/pkg/queue/index/manager.go
  internal/pkg/queue/index/manager_test.go
  internal/pkg/queue/index/recovery.go
  internal/pkg/queue/index/recovery_test.go
  internal/pkg/queue/index/wal.go
  internal/pkg/queue/index/wal_test.go
  internal/pkg/queue/item.go
  internal/pkg/queue/item_test.go
  internal/pkg/queue/metadata.go
  internal/pkg/queue/protobuf/v1/item.pb.go
  internal/pkg/queue/protobuf/v1/item.proto
  internal/pkg/queue/queue.go
  internal/pkg/queue/queue_test.go
  internal/pkg/queue/stats.go
  internal/pkg/seencheck/seencheck.go
Labels: enhancement, internal-only

#114 Fix idna.ToASCII fail on punycode encoded URLs with port
  internal/pkg/utils/url.go
  internal/pkg/utils/url_string.go
  internal/pkg/utils/url_test.go
Labels: bug

#117 Enable `log` package to distribute a stored logger to all other packages
  internal/pkg/crawl/worker.go
  internal/pkg/log/log.go
  internal/pkg/log/withfields.go
  internal/pkg/queue/index/manager.go
  internal/pkg/queue/index/recovery.go
  internal/pkg/queue/index/recovery_test.go
  internal/pkg/queue/queue.go
Labels: bug, enhancement, P1

#119 Change default queue behaviour
  cmd/get.go
  config/config.go
  internal/pkg/crawl/config.go
Labels: enhancement, internal-only, P1

#124 Ingest seeds before starting workers
  internal/pkg/crawl/crawl.go
Labels: bug

#125 Correct seedList enqueuing process
  internal/pkg/crawl/crawl.go
  internal/pkg/queue/enqueue.go
  internal/pkg/queue/handover.go
  internal/pkg/queue/queue.go
  internal/pkg/queue/stats.go
Labels: enhancement, P2

#127 Add Pyroscope profiling support
  cmd/get.go
  config/config.go
  go.mod
  go.sum
  internal/pkg/crawl/config.go
Labels: enhancement

#128 Fix the handover bypass when seeds are loaded from list and handover is disabled
  internal/pkg/crawl/crawl.go
Labels: bug, P1

#129 Add additional tests and validate current URL behavior
  internal/pkg/utils/url.go
  internal/pkg/utils/url_test.go
Labels: enhancement

#133 Add job and WARC prefix to pyroscope tags for better search
  .github/workflows/build.yml
  .github/workflows/go.yml
  internal/pkg/crawl/config.go
Labels: enhancement

#134 fix: recursion present in Telegram URLs
  internal/pkg/crawl/sitespecific/telegram/telegram.go
Labels: bug

#137 Add custom code for Reddit archiving
  internal/pkg/crawl/assets.go
  internal/pkg/crawl/capture.go
  internal/pkg/crawl/extractor/json.go
  internal/pkg/crawl/extractor/json_test.go
  internal/pkg/crawl/extractor/xml.go
  internal/pkg/crawl/outlinks.go
  internal/pkg/crawl/sitespecific/reddit/reddit.go
Labels: enhancement

#138 Add XML extractor tests
  internal/pkg/crawl/extractor/xml_test.go
Labels: enhancement

#139 Fix seencheck re-implementation with current queue
  cmd/get.go
  config/config.go
  internal/pkg/crawl/capture.go
  internal/pkg/crawl/config.go
  internal/pkg/crawl/crawl.go
  internal/pkg/crawl/outlinks.go
Labels: bug, internal-only, P1

#140 Fix worker state panic when current item or URL is nil
  internal/pkg/crawl/worker_pool.go
Labels: bug, P1
