Repository internetarchive/Zeno, pull requests merged in 2025-05, with the labels that each got.

#279 feat: Extract WACZ files from replayweb embeds
  internal/pkg/postprocessor/extractor/html.go
Labels: enhancement

#290 Regex improvements and add strict regex toggle
  cmd/get.go
  internal/pkg/config/config.go
  internal/pkg/postprocessor/extractor/html.go
  internal/pkg/postprocessor/outlinks.go
Labels: enhancement, P1

#294 Resolve panics
  internal/pkg/controler/pipeline.go
  internal/pkg/preprocessor/exclusion_test.go
  internal/pkg/source/hq/consumer.go
  internal/pkg/source/lq/consumer.go
  pkg/models/item_test.go
  pkg/models/url.go
Labels: bug, P1

#299 Refactor HTML unit tests and increase coverage
  internal/pkg/postprocessor/extractor/html_test.go
Labels: coverage

#300 Fix HQ sleep time
  .gitignore
  internal/pkg/source/hq/consumer.go
Labels: bug, P2

#302 Extract iframe SRC as outlinks
  internal/pkg/postprocessor/extractor/html.go
  internal/pkg/postprocessor/extractor/html_test.go
Labels: enhancement, P4
