Repository internetarchive/Zeno, pull requests merged in 2025-08, with the labels that each got.

#428 Add live reload of exclusion lists (and switch to go 1.25)
  cmd/get.go
  go.mod
  internal/pkg/archiver/archiver.go
  internal/pkg/config/config.go
  internal/pkg/config/exclusions.go
  internal/pkg/log/log.go
  internal/pkg/preprocessor/preprocessor.go
Labels: enhancement

#433 Modernize code
  internal/pkg/archiver/ratelimiter/manager_test.go
  internal/pkg/archiver/ratelimiter/ratelimiter_test.go
  internal/pkg/controler/pause/pause.go
  internal/pkg/controler/pause/pause_test.go
  internal/pkg/controler/watchers/warc.go
  internal/pkg/log/ringbuffer/ringbuffer.go
  internal/pkg/log/ringbuffer/ringbuffer_test.go
  internal/pkg/postprocessor/extractor/css_test.go
  internal/pkg/postprocessor/extractor/html.go
  internal/pkg/postprocessor/extractor/json.go
  internal/pkg/postprocessor/extractor/link_header.go
  internal/pkg/postprocessor/extractor/link_header_test.go
  internal/pkg/postprocessor/extractor/xml_test.go
  internal/pkg/postprocessor/outlinks_test.go
  internal/pkg/postprocessor/sitespecific/ina/ina.go
  internal/pkg/reactor/reactor_test.go
  internal/pkg/reactor/state.go
  internal/pkg/stats/rate_test.go
  internal/pkg/stats/stats.go
  internal/pkg/ui/pause.go
  internal/pkg/ui/stats.go
  pkg/models/item.go
  pkg/models/item_test.go
  pkg/models/url_test.go
Labels: enhancement

#435 Create rootContext and share with components
  internal/pkg/consul/consul.go
  internal/pkg/controler/pipeline.go
  internal/pkg/controler/watchers/warc.go
  internal/pkg/finisher/finisher.go
  internal/pkg/postprocessor/postprocessor.go
  internal/pkg/preprocessor/preprocessor.go
  internal/pkg/reactor/reactor.go
  internal/pkg/reactor/reactor_test.go
Labels: enhancement

#441 refactor(test): replace the socket logging with `net.Pipe()`
  cmd/cmd.go
  e2e/e2e.go
  e2e/test/cloudflare204/cloudflare204_test.go
  e2e/test/nonutf8encoding/contenttype/contenttype_test.go
  e2e/test/nonutf8encoding/metacharset/metacharset_test.go
  e2e/test/nxdomain/nxdomain_test.go
  internal/pkg/config/config.go
  internal/pkg/controler/signal.go
  internal/pkg/log/config.go
  internal/pkg/log/log.go
Labels: tests

#445 Add faster domain lookup for domainscrawl
  cmd/get.go
  internal/pkg/config/config.go
  internal/pkg/postprocessor/domainscrawl/domainscrawl.go
  internal/pkg/postprocessor/domainscrawl/domainscrawl_test.go
Labels: enhancement

#356 Headless/Headful mode
  .github/workflows/go.yml
  cmd/get.go
  e2e/test/headless/ok200/config.toml
  e2e/test/headless/ok200/ok200.go
  e2e/test/headless/ok200/ok200_test.go
  go.mod
  go.sum
  internal/pkg/archiver/archiver.go
  internal/pkg/archiver/body.go
  internal/pkg/archiver/connutil/connutil.go
  internal/pkg/archiver/general/archiver.go
  internal/pkg/archiver/general/body.go
  internal/pkg/archiver/headless/README.md
  internal/pkg/archiver/headless/archiver.go
  internal/pkg/archiver/headless/behaviors.js
  internal/pkg/archiver/headless/body.go
  internal/pkg/archiver/headless/browser.go
  internal/pkg/archiver/headless/browser_test.go
  internal/pkg/archiver/headless/bx_logger.go
  internal/pkg/archiver/headless/headless.go
  internal/pkg/archiver/headless/waitgroup.go
  internal/pkg/archiver/warc.go
  internal/pkg/archiver/worker.go
  internal/pkg/config/config.go
  internal/pkg/postprocessor/assets.go
  internal/pkg/postprocessor/extractor/css.go
  internal/pkg/postprocessor/extractor/html.go
  internal/pkg/postprocessor/extractor/html_test.go
  internal/pkg/postprocessor/extractor/json_test.go
  internal/pkg/postprocessor/extractor/link_header.go
  internal/pkg/postprocessor/extractor/link_header_test.go
  internal/pkg/postprocessor/extractor/mode.go
  internal/pkg/postprocessor/extractor/object_storage.go
  internal/pkg/postprocessor/extractor/pdf.go
  internal/pkg/postprocessor/extractor/pdf_test.go
  internal/pkg/postprocessor/extractor/xml.go
  internal/pkg/postprocessor/extractor/xml_test.go
  internal/pkg/postprocessor/item.go
  internal/pkg/postprocessor/outlinks.go
  internal/pkg/postprocessor/sitespecific/reddit/api.go
  internal/pkg/postprocessor/sitespecific/truthsocial/account.go
  internal/pkg/preprocessor/preprocessor.go
  pkg/models/url.go
Labels: enhancement, GSoC

#449 Add --warc-digest-algorithm
  cmd/get.go
  go.mod
  go.sum
  internal/pkg/archiver/warc.go
  internal/pkg/config/config.go
Labels: enhancement

#429 Make Zeno to be signalable by HQ via websocket
  internal/pkg/source/hq/websocket.go
Labels: enhancement, GSoC

#451 Add support for confirmed messages through WS
  internal/pkg/source/hq/websocket.go
Labels: enhancement

#442 More versatile HQ client init
  internal/pkg/controler/pipeline.go
  internal/pkg/source/hq/hq.go
  internal/pkg/source/hq/websocket.go
Labels: enhancement
