Repository internetarchive/Zeno, pull requests merged in 2025-07, with the labels that each got.

#377 Implement a shared interface for `source` so anyone can implement their own source of items
  internal/pkg/controler/pipeline.go
  internal/pkg/preprocessor/preprocessor.go
  internal/pkg/source/hq/consumer.go
  internal/pkg/source/hq/finisher.go
  internal/pkg/source/hq/hq.go
  internal/pkg/source/hq/producer.go
  internal/pkg/source/hq/seencheck.go
  internal/pkg/source/hq/websocket.go
  internal/pkg/source/lq/client.go
  internal/pkg/source/lq/consumer.go
  internal/pkg/source/lq/finisher.go
  internal/pkg/source/lq/lq.go
  internal/pkg/source/lq/producer.go
  internal/pkg/source/source.go
Labels: enhancement

#383 Fix: discard hooks does not interrupt downloads
  internal/pkg/archiver/archiver.go
  internal/pkg/archiver/discard/README.md
Labels: bug

#380 feat: add initial revision to add content length based prometheus stats
  go.mod
  go.sum
  internal/pkg/archiver/warc.go
  internal/pkg/controler/watchers/warc.go
  internal/pkg/stats/methods.go
  internal/pkg/stats/prometheus.go
  internal/pkg/stats/stats.go
Labels: enhancement

#385 Fix: `BadStatusCode` responses are not handled by `copyWithTimeout()`
  internal/pkg/archiver/archiver.go
Labels: bug

#403 E2E testing and start tracking coverage
  .github/workflows/go.yml
  cmd/cmd.go
  e2e/e2e.go
  e2e/log/log.go
  e2e/log/log_test.go
  e2e/log/testdata/zeno.log.data
  e2e/log/util.go
  e2e/test/cloudflare204/cloudflare204_test.go
  e2e/test/nxdomain/config.toml
  e2e/test/nxdomain/nxdomain_test.go
  go.mod
  go.sum
  internal/pkg/config/config.go
  internal/pkg/controler/signal.go
  internal/pkg/log/config.go
  internal/pkg/log/log.go
Labels: github_actions, coverage, GSoC, tests
