Repository internetarchive/Zeno, pull requests merged in 2025-09, with the labels that each got.

#456 Add support for Sentry
  cmd/get.go
  cmd/get_hq.go
  cmd/get_url.go
  cmd/utils.go
  go.mod
  go.sum
  internal/pkg/config/config.go
  internal/pkg/stats/prometheus.go
Labels: enhancement

#457 Bump gowarc to v0.8.88
  go.mod
  go.sum
Labels: dependencies

#423 dependency: upgrade go-css-lexer to v0.1.0
  go.mod
  go.sum
  internal/pkg/postprocessor/extractor/css.go
  internal/pkg/postprocessor/extractor/css_test.go
  internal/pkg/postprocessor/extractor/css_util.go
  internal/pkg/postprocessor/extractor/html.go
Labels: dependencies, GSoC

#452 Optimize domainscrawl domain matching
  e2e/test/cloudflare204/cloudflare204_test.go
  e2e/test/domainscrawl/config.toml
  e2e/test/domainscrawl/domainscrawl_test.go
  e2e/test/headless/ok200/ok200_test.go
  e2e/test/nonutf8encoding/contenttype/contenttype_test.go
  e2e/test/nonutf8encoding/metacharset/metacharset_test.go
  e2e/test/nxdomain/nxdomain_test.go
  go.mod
  go.sum
  internal/pkg/postprocessor/domainscrawl/README.md
  internal/pkg/postprocessor/domainscrawl/domainscrawl.go
  internal/pkg/postprocessor/domainscrawl/domainscrawl_bench_test.go
  internal/pkg/postprocessor/domainscrawl/domainscrawl_test.go
  internal/pkg/postprocessor/domainscrawl/reversehost.go
  internal/pkg/postprocessor/domainscrawl/reversehost_test.go
  internal/pkg/postprocessor/domainscrawl/tree.go
  internal/pkg/postprocessor/domainscrawl/tree_test.go
Labels: enhancement

#459 Fix domainscrawl race in tests
  internal/pkg/postprocessor/domainscrawl/domainscrawl.go
  internal/pkg/postprocessor/domainscrawl/domainscrawl_test.go
Labels: bug

#466 refactor `TestPauseResumeE2E` with synctest for accuracy
  internal/pkg/controler/pause/pause_test.go
Labels: tests
