Repository internetarchive/Zeno, pull requests merged in 2025-06, with the labels that each got.

#324 Replacing the regex-based CSS extractor with a standard CSS parser
  go.mod
  go.sum
  internal/pkg/postprocessor/extractor/css.go
  internal/pkg/postprocessor/extractor/css_test.go
  internal/pkg/postprocessor/extractor/html.go
Labels: GSoC

#339 Extracting URLs from CSS `@import` rule
  internal/pkg/postprocessor/extractor/css.go
  internal/pkg/postprocessor/extractor/css_test.go
  internal/pkg/postprocessor/extractor/html.go
Labels: enhancement, extractor, GSoC

#357 Update gowarc and add Doppelganger support
  cmd/get.go
  cmd/get_url.go
  go.mod
  go.sum
  internal/pkg/archiver/archiver.go
  internal/pkg/archiver/discard/discard.go
  internal/pkg/archiver/warc.go
  internal/pkg/config/config.go
  internal/pkg/controler/watchers/warc.go
  internal/pkg/postprocessor/sitespecific/ina/ina.go
  internal/pkg/stats/methods.go
  internal/pkg/stats/prometheus.go
  internal/pkg/stats/stats.go
Labels: enhancement
