Repository internetarchive/Zeno, pull requests merged in 2025-02, with the labels that each got.

#185 Add reddit support to v2
  .gitignore
  internal/pkg/postprocessor/outlinks.go
  internal/pkg/postprocessor/sitespecific/reddit/api.go
  internal/pkg/postprocessor/sitespecific/reddit/reddit.go
  internal/pkg/preprocessor/preprocessor.go
Labels: enhancement

#211 Rework preprocessor concurrency
  internal/pkg/controler/pipeline.go
  internal/pkg/preprocessor/preprocessor.go
Labels: v2

#212 Rework archiver concurrency
  internal/pkg/archiver/archiver.go
Labels: v2

#209 Rework concurrency for pipeline stages
  internal/pkg/archiver/archiver.go
  internal/pkg/controler/channels.go
  internal/pkg/controler/pipeline.go
  internal/pkg/finisher/finisher.go
  internal/pkg/postprocessor/postprocessor.go
  internal/pkg/preprocessor/preprocessor.go
  internal/pkg/stats/methods.go
  internal/pkg/stats/stats.go
Labels: v2

#222 Drop item.seed attribute
  internal/pkg/controler/pipeline.go
  internal/pkg/postprocessor/extractor/base_test.go
  internal/pkg/postprocessor/extractor/html_test.go
  internal/pkg/postprocessor/extractor/resolve_test.go
  internal/pkg/postprocessor/item.go
  internal/pkg/reactor/reactor_test.go
  internal/pkg/source/hq/consumer.go
  pkg/models/item.go
  pkg/models/item_dedupe.go
  pkg/models/item_dedupe_test.go
  pkg/models/item_misc_test.go
  pkg/models/item_test.go
Labels: enhancement, v2

#224 Reduce Pyroscope upload rate to default value (15s)
  cmd/get_hq.go
Labels: v2

#223 Fix reactor tests concurrency issues
  internal/pkg/reactor/reactor_test.go
Labels: bug, v2

#226 Optimize models `URLToString`
  pkg/models/url.go
  pkg/models/url_test.go
Labels: enhancement, internal-only, v2

#233 Expose Prometheus metrics and make Zeno self-declare as a Consul service for it's metrics to be collected automatically
  cmd/get.go
  go.mod
  go.sum
  internal/pkg/api/api.go
  internal/pkg/config/config.go
  internal/pkg/consul/consul.go
  internal/pkg/controler/pipeline.go
  internal/pkg/stats/methods.go
  internal/pkg/stats/prometheus.go
  internal/pkg/stats/stats.go
  internal/pkg/ui/stats.go
Labels: enhancement, v2

#236 Revamp WARC writing queue watcher
  internal/pkg/archiver/archiver.go
  internal/pkg/archiver/warc.go
  internal/pkg/controler/pipeline.go
  internal/pkg/controler/watchers/warc.go
Labels: enhancement, v2
